version: '2'
services:
  homepage:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      TO_EMAIL: $TO_EMAIL
      SMTP_HOST: $SMTP_HOST
      SMTP_SECURE: $SMTP_SECURE
      SMTP_PORT: $SMTP_PORT
      SMTP_SERVICE: $SMTP_SERVICE
      SMTP_AUTH_USER: $SMTP_AUTH_USER
      SMTP_AUTH_PASS: $SMTP_AUTH_PASS
